### ISSUE TITLE
Remove download of external ressources

### ISSUE THREAD

**Issue by jaschaurbach** [LittleLink-Custom/Aurora#1] opened 2023-03-27 20:40 UTC
Here int the css https://github.com/LittleLink-Custom/Aurora/blob/629dcb64673e9caa24ffcbf777d2a8dd2189c558/skeleton-auto.css#L68 the background images gets loaded from GitHub. 

As per good GDPR-preactice I need to inform my users about this. It was just luck that I saw it. 
Same is with https://fonts.bunny.net/roboto/files/roboto-latin-400-normal.woff2 - it was luck as well that I saw it. I would need to write it into my Datenschutzerklärung and inform users about that as well. 

External Resources are pain, especially when it comes to companies in the US which I never had a contract with (bunny.net).

Thanks for considering because I love your theme and do not want to fork it in case it will get updates and I miss them then.

**Comment by MagicLike** [comment] 2023-03-28 08:30
We already tried to minimise all external resources. The GitHub one is a real bummer @JulianPrieber. But - just a short information for you: (fonts.)bunny.net is from Slovenia and not from the USA - maybe we should consider hosting all fonts inside LLC anyway...

**Comment by JulianPrieber** [comment] 2023-03-28 10:59
> Thanks for considering because I love your theme and do not want to fork it in case it will get updates and I miss them then.

You could make a fork and then commit your changes. I'm happy with all the help I can get.

> It was luck as well that I saw it. I would need to write it into my Datenschutzerklärung and inform users about that as well.

I don't want to alarm anyone, but all our themes do something like this in one form or the other.

<br>

The good news is that themes don't have to rely on external resources anymore. Since themes v2 themes have the option to include assets in all formats. In addition, themes can make use of already implemented assets like the font here.


Documentation on how to do it is on the [themes repo](https://github.com/JulianPrieber/llc-themes/tree/main/contributing#24-adding-custom-assets).

This has been on my radar since the addition of themes, that's one reason why I implemented v2. If I implement this, this will break all themes before themes v1. But I think enough time has passed to assume anyone updating their themes has adopted the new system by now.

I just haven't gotten to reworking every theme yet. I might be able to do a couple next week or so. Then gradually update every theme.

**Comment by JulianPrieber** [comment] 2023-03-31 12:14
Well this is new :grimacing: 
![chrome_2HK2x4v09f](https://user-images.githubusercontent.com/60265788/229116231-6cb11cd1-892d-438f-87ba-88473f7296b7.jpg)

**Comment by JulianPrieber** [comment] 2023-03-31 12:40
> Well this is new 😬

I couldn't reproduce this since. Not sure what's happening

**Comment by JulianPrieber** [comment] 2023-03-31 12:47
![chrome_96NNwDBkCi](https://user-images.githubusercontent.com/60265788/229123695-ac06c832-d324-4748-8f29-2e2f92b700b8.png)

There it is again. Not sure what's causing it. I can reproduce this on all my docker instances, but not on my web instance. Might be a caching issue there, but not on the docker, so I think this needs to be investigated before the release.

**Comment by jaschaurbach** [comment] 2023-04-03 15:12
I can not reproduce this. Do not know what is happening there.

**Comment by JulianPrieber** [comment] 2023-04-03 16:22
For some reason, I can only reproduce this on docker instances. 
Not sure what's happening here.

**Comment by lastsamurai26** [comment] 2023-05-16 11:50
Should be fixed with version 1.8

**Closed as completed by lastsamurai26** 2023-05-16 11:50 UTC
